name: Robot Framework - Python
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "master" ]
 
permissions:
  contents: read
 
jobs:
  test:
    runs-on: windows-latest
     
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.8
   
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-browser
               
      - name: Initialize Browser Library
        run: rfbrowser init
      - name: Test with RobotFramework
        run: robot .
      - name: Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: reports                # Name of the folder
          path: report.html log.html output.xml         # Path to test results
         
